# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: 'npm'
    directory: '/' # Location of package manifests (package.json file)
    schedule:
      # Runs once each month, on the first day of the month.
      interval: 'monthly'
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: 'all'
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: 'npm'
    # Specify labels for npm pull requests
    labels:
      - 'npm'
      - 'dependencies'
    # Allow up to 10 open pull requests for npm dependencies (default is 5)
    open-pull-requests-limit: 10
    # Add reviewers
    reviewers:
      - 'anhtuta'
